2011-03-31  Laszlo Peter  <laszlo.peter@oracle.com>
	* Makefile.am: add ips-dependency-generator
	* NEWS: lots of changes detailed
	* configure.in: locate utilities needed by pkgbuild
	* ips-dependency-generator: (new) script that generates IPS
	  dependencies given a list of files to be packaged
	* ips_utils.pm: allow https IPS repos
	* macros.in: define additional macros to match RPM
	* pkgbuild.in: simplify
	* pkgbuild.pl.in: loads of changes - detailed in NEWS
	* pkgdb.pm.in: escape @ FMRI regexps
	* pkgtool.in: simplify
	* pkgtool.pl: loads of changes - detailed in NEWS
	* rpm_file.pm: support excluded and preserved files
	* rpm_package.pm: use a package counter (id) so that packages
	  can be positively identified and other changes detailed in NEWS
	* rpm_spec.pm.in: loads of changes - detailed in NEWS
	* spectool.in: simplify
	* spectool.pl: implement get_all_requires and -a option of
	  get_package_names (prints obsolete/renamed packages)

diff --git a/pkgtool.in b/pkgtool.in
--- a/pkgtool.in
+++ b/pkgtool.in
@@ -25,12 +25,11 @@
 #  Authors:  Laszlo Peter  <laca@sun.com>
 #
 
-origwd=`pwd`;
-mydir=$(cd $(dirname $0); pwd);
-
-if [ `uname -s` = SunOS ]; then
+if [ "`uname -s`" = "SunOS" ]
+then
     /usr/bin/id | /usr/bin/grep '^uid=0(' > /dev/null 2>&1
-    if [ $? = 0 ]; then
+    if [ $? = 0 ]
+    then
 	echo "Building as root is dangerous and is no longer supported."
 	echo "Please use a non-privileged account for running pkgtool."
 	echo "When using pkgtool modes that involve package installation, you need an"
@@ -40,20 +39,21 @@ if [ `uname -s` = SunOS ]; then
     fi
 fi
 
+pkgbuild_prefix="@PKGBUILD_PREFIX@"
 pkgbuild_libdir="@PKGBUILD_LIBDIR@"
+pkgbuild_bindir="${pkgbuild_prefix}/bin"
+pkgbuild_wrapper="${pkgbuild_bindir}/pkgbuild"
+pkgtool_implementation="${pkgbuild_libdir}/pkgtool.pl"
 
-if [ ! -f "$pkgbuild_libdir/pkgbuild.pl" ]; then
-    echo "ERROR: pkgbuild not found." 1>&2
+if [ ! -d "${pkgbuild_prefix}" -o \
+     ! -d "${pkgbuild_libdir}" -o \
+     ! -d "${pkgbuild_bindir}" -o \
+     ! -x "${pkgbuild_wrapper}" -o \
+     ! -f "${pkgtool_implementation}" ]
+then
+    echo "${0}: FATAL ERROR - pkgbuild implementation not found." 1>&2
     exit 1
 fi
 
-pkgbuild_prefix="$pkgbuild_libdir/../.."
-pkgbuild_prefix=$(cd "${mydir}/.."; pwd)
-
-if [ ! -x "$pkgbuild_prefix/bin/pkgbuild" ]; then
-    echo "ERROR: pkgbuild not found." 1>&2
-    exit 1
-fi
-
-# pass in the full path to pkgbuild as the first arg
-exec @PERL@ -I "$pkgbuild_libdir" $pkgbuild_libdir/pkgtool.pl "$pkgbuild_prefix/bin/pkgbuild" "${@}"
+# Pass in the full path to the pkgbuild wrapper as the first command line argument
+exec "@PERL@" -I "${pkgbuild_libdir}" "${pkgtool_implementation}" "${pkgbuild_wrapper}" "${@}"
diff --git a/spectool.in b/spectool.in
--- a/spectool.in
+++ b/spectool.in
@@ -25,9 +25,21 @@
 #  Authors:  Laszlo Peter  <laca@sun.com>
 #
 
-origwd=`pwd`;
-mydir=$(cd $(dirname $0); pwd);
-pkgbuild_dir="$mydir/../lib/pkgbuild-@PKGBUILD_VERSION@"
 pkgbuild_prefix="@PKGBUILD_PREFIX@"
+pkgbuild_libdir="@PKGBUILD_LIBDIR@"
+pkgbuild_bindir="${pkgbuild_prefix}/bin"
+pkgbuild_wrapper="${pkgbuild_bindir}/pkgbuild"
+spectool_implementation="${pkgbuild_libdir}/spectool.pl"
 
-exec @PERL@ -I $pkgbuild_dir $pkgbuild_dir/spectool.pl "$pkgbuild_prefix/bin/pkgbuild" "${@}"
+if [ ! -d "${pkgbuild_prefix}" -o \
+     ! -d "${pkgbuild_libdir}" -o \
+     ! -d "${pkgbuild_bindir}" -o \
+     ! -x "${pkgbuild_wrapper}" -o \
+     ! -f "${spectool_implementation}" ]
+then
+    echo "${0}: FATAL ERROR - pkgbuild implementation not found." 1>&2
+    exit 1
+fi
+
+# Pass in the full path to the pkgbuild wrapper as the first command line argument
+exec "@PERL@" -I "${pkgbuild_libdir}" "${spectool_implementation}" "${pkgbuild_wrapper}" "${@}"
